### ISSUE TITLE
Extension Tab Not Showing

### ISSUE THREAD

**Issue by thatoneguydan** [jtydhr88/sd-3dmodel-loader#21]
I tried installing first from the extension browser directly within Automatic1111, the tab didn't show after clicking "apply and restart ui"

I then deleted it and installed directly from URL. It still didn't show, and now the "available" tab from within the UI won't show any extensions. Not sure if that's related.

I'm pretty new to SD, so I'm not sure what other info or logs you need to diagnose the issue. I will try to provide.

**Comment by thatoneguydan** [comment]
Yes it's there.

I relaunched SD and noticed this error text:

Error executing callback ui_tabs_callback for C:\Program Files\Stable Diffusion\stable-diffusion-webui\extensions\3d model\scripts\main.py
Traceback (most recent call last):
  File "C:\Program Files\Stable Diffusion\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "C:\Program Files\Stable Diffusion\stable-diffusion-webui\extensions\3d model\scripts\main.py", line 54, in on_ui_tabs
    select_target_index = gr.Dropdown([str(i) for i in range(opts.control_net_max_models_num)],
  File "C:\Program Files\Stable Diffusion\stable-diffusion-webui\modules\shared.py", line 552, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'control_net_max_models_num'

**Comment by thatoneguydan** [comment]
Thanks, I didn't realize it was dependent on controlnet. After installing, it works.

Do you have any recommendations on what controlnet processor and model reads the 3d models well?

**Comment by shineway14** [comment]
> well, ControlNet is a big topic, you can refer its home here https://github.com/Mikubill/sd-webui-controlnet for more information. different Preprocessor/model has different purpose, my frequent ones are openpose, normal map and canny.
> 
> I will close this issue for now.

It didn't work at sd webui 1.3
