### ISSUE TITLE
glitched ui ui

### ISSUE THREAD

**Issue by Enferlain** [jtydhr88/sd-3dmodel-loader#51]
![image](https://user-images.githubusercontent.com/15861396/235807372-5c8fe691-fe99-47b9-ab84-e47904c1deb4.png)

python: 3.10.11  •  torch: 1.13.1+cu116  •  xformers: 0.0.16  •  gradio: 3.16.2  •  commit: [a9fed7c3]

Is this normal or only me? Help pls!

**Comment by Enferlain** [comment]
Yes, but they're spread out very far apart and I can't realistically use any of the settings because it can scroll down forever

**Comment by Enferlain** [comment]
```
Error running process: /content/drive/.shortcut-targets-by-id/1L0fJf5wzsbvNAkNMlHU_amjVtMuFfIUR/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
Traceback (most recent call last):
  File "/content/drive/.shortcut-targets-by-id/1L0fJf5wzsbvNAkNMlHU_amjVtMuFfIUR/stable-diffusion-webui-colab/stable-diffusion-webui/modules/scripts.py", line 409, in process
    script.process(p, *script_args)
  File "/content/drive/.shortcut-targets-by-id/1L0fJf5wzsbvNAkNMlHU_amjVtMuFfIUR/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py", line 267, in process
    self, p ,breaks = inpaintmaskdealer(self, p, bratios, usebase, polymask, comprompt, comnegprompt)
  File "/content/drive/.shortcut-targets-by-id/1L0fJf5wzsbvNAkNMlHU_amjVtMuFfIUR/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/regions.py", line 647, in inpaintmaskdealer
    m = 1 - tm
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

```
Hmm. Any idea what this is?

**Comment by Enferlain** [comment]
Thanks, I'll try it and see how it goes

**Comment by Enferlain** [comment]
Yeah I haven't been able to try yet, but I'll do it when I wake up.
